name: Deploy HTML no GitHub Pages

on:
  push:
    branches:
      - main   # dispara quando fizer push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Confere index.html na raiz
        run: |
          echo "Listando arquivos na raiz:"
          ls -la
          if [ ! -f "./index.html" ]; then
            echo "ERRO: index.html não encontrado na raiz. Ajuste publish_dir no workflow."
            exit 1
          fi

      - name: Publicar no GitHub Pages (branch gh-pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
